### ISSUE TITLE
Debug PostProcessor?

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#107]
Having a [Debug PostProcessor](https://jmeter.apache.org/usermanual/component_reference.html#Debug_PostProcessor) would be cool!

Sample code:

https://github.com/pragmatictesters/Pragmatic-Learning-JMeter-Examples/blob/master/TestPlan-StackOverFlow-68706730-JSON.jmx

thx

**Comment by smicyk** [comment]
Done in #108
