### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#131]
Getting:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/Users/myid/.sdkman/candidates/groovy/current/lib/groovy-3.0.20.jar) to method sun.nio.fs.UnixFileSystem.getPath(java.lang.String,java.lang.String[])
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

There has been a similar issue at https://github.com/arch-noob/filebot/issues/14, but trying to add the `--add-opens=java.base/sun.nio.fs=ALL-UNNAMED` hinted by its solution is not working for me, and I'm still getting the above.

Any way to suppress this warning pls?

**Comment by smicyk** [comment]
Hi, this is something rally can be removed in current groovy version but in the examples folder you can see how to properly pass --add-opens so groovy can pick it up e.g.  [standalone](/smicyk/groovy-jmeter/tree/develop/examples/standalone) Add in #133.
