### ISSUE TITLE
[feature] test fragment for inclusion

### ISSUE THREAD

**Issue by suntong** [smicyk/groovy-jmeter#49]
Hi, Interesting project that I just noticed today. Quick question, 

Does groovy-jmeter support feature similiar to jmeter fragment so that people can define common scripts to be included in other scripts? 

thx

**Comment by smicyk** [comment]
Hi, 

currently the there is no element which works as jmeter fragment and module controller.

The alternative to that is to use __insert__ element which can include other script into your main script. The idea is similar but in reality it does not reference the fragment but includes its contents to main script. You can check [examples](/smicyk/groovy-jmeter/tree/develop/examples/structure) folder to see it in action.

Hope that helps.

**Comment by suntong** [comment]
Ah, yes, that's a good workaround. and thanks for the fast response BTW.

Is there any plan to add support for jmeter fragment and module controller in near or far future?

**Comment by smicyk** [comment]
Hi, currently I don't have a plan to do it. The way how it works in jmeter makes it a little bit akward right now. Probably it needs some more rethinking to be usable.

**Comment by suntong** [comment]
OK, fair enough. 
Close it for now...
