### ISSUE TITLE
Include vs insert 

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#55]
The

- https://github.com/smicyk/groovy-jmeter/wiki/reference#include
- https://github.com/smicyk/groovy-jmeter/wiki/reference#insert

What are the differences between the two?

The `include` _"defines 'Include' controller"_, does it mean I can use it to include other existing JMeter test fragments? thx.

**Comment by smicyk** [comment]
Yes, the __include__ is same as Include controller in JMeter so you should be able to add .jmx files if you have one.

The __insert__ in specific to groovy scripts and it give possibility to insert other fragment of groovy script code.

**Comment by AntonioSun** [comment]
Gotcha. thx!
