### ISSUE TITLE
jmespath support

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#56]
The JMeter community recommends jmespath over JSON Path -- It is said in 

https://www.blazemeter.com/blog/the-jmeter-json-jmespath-extractor-andassertion-a-guide

> this JSON Path approach had (and still has) some disadvantages ... 
> The JMESPath (has) Advantages and Benefits ...

Please consider adding jmespath support. thx

**Comment by smicyk** [comment]
Will do.
