### ISSUE TITLE
[feature] Add descriptions to User Variables element

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#68]
Please add the description field to argument, which currently only allow name & value.

It'll be the extra `<stringProp name="Argument.desc">descriptions</stringProp>` field in JMeter. 

thanks

**Comment by smicyk** [comment]
Hi, can you specify where you would like to have it? Currently only User Variables element has arguments where you can define description e.g.

```groovy
plan {
    variables {
        variable name: 'test', value: 'test', description: 'test'
   }
}
```

The __argument__ keyword in Test Plan and Backend Listener doesn't have that field (at least in GUI). Would you like to have such possibility in Test Plan and Backend Listener?

**Comment by AntonioSun** [comment]
I only see `variables` in

https://github.com/smicyk/groovy-jmeter/wiki/reference#variables

and it is having entirely different fields. 

> Currently only User Variables element has arguments where you can define description e.g.
> 
> ```groovy
> plan {
>     variables {
>         variable name: 'test', value: 'test', description: 'test'
>    }
> }
> ```

So if it is already done, maybe it is just to update the doc to close this issue.

**Comment by smicyk** [comment]
OK. I think you need this https://github.com/smicyk/groovy-jmeter/wiki/reference#variable. I see now that I have problem with this reference page as there couple of links which points to the different places.

Anyway I will close the issue since the feature is available.
