### ISSUE TITLE
[feature] Jmeter Timers

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#69]
From https://www.guru99.com/timers-jmeter.html

> By default, JMeter sends the request without pausing between each request. In that case, JMeter could overwhelm your test server by making too many requests in a short amount of times.
> **in real life visitors do not arrive at a website all at the same time, but at different time intervals. So Timer will help mimic the real-time behavior.**

Please add them, at least the _Uniform random timer_ one, which would be most useful. thx.

**Comment by AntonioSun** [comment]
https://github.com/smicyk/groovy-jmeter/wiki#timer
Strange, I tried to find it before posting.

**Comment by smicyk** [comment]
Hi, please check also https://github.com/smicyk/groovy-jmeter/wiki/Components-Status where you have JMeter component name (as on JMeter Page) and implementation status in groovy-jmeter.

Hope it helps.
