### ISSUE TITLE
[Q] POST Text instead of Params

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#74]
Following up on #71, here is another POST outlier. 

First of all, here is a sample of normal POST in a .har file:

<img width="385" alt="image" src="https://user-images.githubusercontent.com/2840074/172285192-c89efed9-09cb-40c4-b01c-0e0540c1d108.png">

The `POST` has `Params` in `PostData`.

Now,

<img width="373" alt="image" src="https://user-images.githubusercontent.com/2840074/172285305-bef70a2c-493e-445c-ad1a-a517c9c18868.png">

This one, The `POST` has `Text ` in `PostData` instead.

How to send such Text in POST?

Would that be something like this?

                http('POST /url/...') {
                    body "POST Text here"
                }

**Comment by smicyk** [comment]
Hi, if POST request is not form data you just use __body__ to sent any data with the POST. Remember that you need to set header with Content-Type 'application/json'.

I don't know if you try but https://github.com/smicyk/groovy-harventer but it converts .har to groovy files. It should handle it I hope at least.

**Comment by AntonioSun** [comment]
Thank you for all your answers.
