### ISSUE TITLE
Debug Sample 

### ISSUE THREAD

**Issue by AntonioSun** [smicyk/groovy-jmeter#92]
From

```
      debug displayJMeterVariables: true, displayJMeterProperties: true
```

I'm getting:

<img width="144" alt="image" src="https://user-images.githubusercontent.com/2840074/178069949-19e73bb5-5c5d-4b25-9f2c-b5a1fd12beb6.png">

I.e., the `displayJMeterProperties: true` has no effect.

**Comment by smicyk** [comment]
Fixed with #97
